### ISSUE TITLE
CompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack.

### ISSUE THREAD

**Issue by ZCalz** [nathandem/uloan#7]
This issue is present when attempting to deploy code through remix. It also appears when verifying and publishing the code on etherscan. 

A commentary on this issue made in forum link here: https://forum.openzeppelin.com/t/stack-too-deep-when-compiling-inline-assembly/11391/6

**Comment by nathandem** [comment]
Optimizing the compilation solves the issue with hardhat (https://github.com/nathandem/uloan/blob/master/apps/uloan-contract/hardhat.config.js#L25-L28). If remix doesn't offer this option, consider installing the project natively 👍
